apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: private-api
build:
  local:
    concurrency: 0

  tagPolicy:
    # envTemplate:
    #   template: "{{.APP_VERSION}}"
    # gitCommit:
    #   variant: AbbrevCommitSha
    #   prefix: "api-"
    customTemplate:
      template: "{{.PREF}}_{{.SUFF}}"
      components:
        - name: PREF
          dateTime:
            format: "2006-01-02"
            timezone: "Local"
        - name: SUFF
          gitCommit:
            variant: AbbrevCommitSha

  artifacts:
  - image: cachac/kubelabs_privateapi_skaffold
    docker:
      dockerfile: Dockerfile
      # buildArgs:
      #   APP_ENV: "nnnnnnn"

# manifests:
#   rawYaml:
#   - kube/ns.yaml
#   - kube/deploy.yaml
#   - kube/svc.yaml

profiles:
  - name: dev
    # activation:
    #   - kubeContext: xyz

    # patches:
    #   - op: replace
    #     path:  /build/artifacts/0/docker/buildArgs/APP_ENV
    #     value: "{{.APP_ENV_DEV}}"

    manifests:
      kustomize:
        paths:
          - kustomize/overlays/dev

  - name: stage
    # activation:
    #   - kubeContext: microk8s
    # patches:
    #   - op: replace
    #     path:  /build/artifacts/0/docker/buildArgs/APP_ENV
    #     value: "{{.APP_ENV_STAGE}}"

    manifests:
      kustomize:
        paths:
          - kustomize/overlays/stage
