apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: private-dev

commonLabels:
  app: private-api
  env: dev

resources:
  - ns.yaml
  - ../../base

patchesStrategicMerge:
  - deploy-strategic-patch.yaml
