apiVersion: v1
kind: Service
metadata:
  name: svc-public-api
  namespace: public

spec:
  type: ClusterIP
  ports:
  - name: http-publicapi
    port: 3000
    targetPort: 3000

  - name: http-healthcheck
    port: 3080
    targetPort: 3080

  selector:
    app: public-api
